import { StyleSheet, useColorScheme } from 'react-native';

export const useHomeStyles = () => {
  const colorScheme = useColorScheme();
  const isDark = colorScheme === 'dark';

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: isDark ? '#181a20' : '#f6f8fa',
      paddingTop: 0,
      paddingBottom: 0,
      paddingHorizontal: 0,
    },
    gradient: {
      flex: 1,
      paddingTop: 0,
      paddingBottom: 0,
      paddingHorizontal: 0,
    },
    headerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingTop: 15,
      paddingBottom: 18,
      paddingHorizontal: 24,
      backgroundColor: isDark ? '#23262f' : '#fff',
      borderBottomLeftRadius: 24,
      borderBottomRightRadius: 24,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 2,
    },
    logo: {
      width: 44,
      height: 44,
      borderRadius: 12,
      backgroundColor: isDark ? '#23262f' : '#fff',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 2,
    },
    appName: {
      flex: 1,
      fontSize: 28,
      fontWeight: 'bold',
      textAlign: 'center',
      fontFamily: 'Inter_700Bold',
      color: isDark ? '#fff' : '#1e293b',
      letterSpacing: 0.5,
    },
    avatarBox: {
      width: 44,
      height: 44,
      borderRadius: 16,
      backgroundColor: isDark ? '#23262f' : '#e0e7ef',
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 2,
    },
    avatar: {
      width: 36,
      height: 36,
      borderRadius: 12,
    },
    divider: {
      height: 1,
      backgroundColor: isDark ? '#23262f' : '#e0e7ef',
      marginHorizontal: 24,
      borderRadius: 2,
      opacity: 0.7,
      marginVertical: 8,
    },
    savingCard: {
      marginTop: 16,
      borderRadius: 32,
      padding: 32,
      alignItems: 'center',
      backgroundColor: isDark ? '#23262f' : '#fff',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 16,
      elevation: 8,
      marginHorizontal: 16,
      marginBottom: 18,
    },
    savingLabel: {
      fontSize: 18,
      fontWeight: '500',
      fontFamily: 'Inter_500Medium',
      color: isDark ? '#94a3b8' : '#64748b',
    },
    savingAmount: {
      fontSize: 44,
      fontWeight: 'bold',
      marginVertical: 6,
      fontFamily: 'Inter_700Bold',
      color: '#1fa97c',
      letterSpacing: 1,
    },
    savingSub: {
      fontSize: 15,
      marginBottom: 18,
      fontFamily: 'Inter_400Regular',
      color: isDark ? '#94a3b8' : '#64748b',
    },
    actionRow: {
      flexDirection: 'row',
      width: '100%',
      justifyContent: 'space-between',
      marginTop: 10,
      gap: 12,
    },
    addBtn: {
      flex: 1,
      borderRadius: 20,
      marginRight: 8,
      paddingVertical: 16,
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'center',
      backgroundColor: '#1fa97c',
      shadowColor: '#1fa97c',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 4,
    },
    addBtnText: {
      fontWeight: 'bold',
      fontSize: 18,
      fontFamily: 'Inter_700Bold',
      color: '#fff',
      letterSpacing: 0.5,
    },
    withdrawBtn: {
      flex: 1,
      borderRadius: 20,
      marginLeft: 8,
      paddingVertical: 16,
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'center',
      backgroundColor: '#1fa97c',
      borderWidth: 2,
      borderColor: '#e74c3c',
      shadowColor: '#e74c3c',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.10,
      shadowRadius: 8,
      elevation: 4,
    },
    withdrawBtnText: {
      fontWeight: 'bold',
      fontSize: 18,
      fontFamily: 'Inter_700Bold',
      color: '#fff',
      letterSpacing: 0.5,
    },
    card: {
      borderRadius: 28,
      marginHorizontal: 16,
      marginTop: 18,
      padding: 22,
      backgroundColor: isDark ? '#23262f' : '#fff',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 3,
    },
    cardTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      marginBottom: 12,
      fontFamily: 'Inter_700Bold',
      color: isDark ? '#fff' : '#1e293b',
    },
    historyRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 14,
      paddingVertical: 4,
    },
    circle: {
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
      backgroundColor: isDark ? '#181a20' : '#f1f5f9',
    },
    plus: {},
    minus: {},
    circleText: {
      fontWeight: 'bold',
      fontSize: 20,
      color: '#1fa97c',
    },
    historyLabel: {
      fontSize: 16,
      fontWeight: '600',
      fontFamily: 'Inter_500Medium',
      color: isDark ? '#fff' : '#1e293b',
    },
    historyDate: {
      fontSize: 13,
      fontFamily: 'Inter_400Regular',
      color: isDark ? '#94a3b8' : '#64748b',
    },
    historyId: {
      fontSize: 13,
      marginLeft: 8,
      fontFamily: 'Inter_400Regular',
      color: '#94a3b8',
    },
    transRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 14,
      paddingVertical: 4,
    },
    transIconBox: {
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
      backgroundColor: isDark ? '#181a20' : '#f1f5f9',
    },
    transIcon: {
      width: 20,
      height: 20,
      borderRadius: 6,
    },
    transLabel: {
      fontSize: 16,
      fontWeight: '600',
      fontFamily: 'Inter_500Medium',
      color: isDark ? '#fff' : '#1e293b',
    },
    transDate: {
      fontSize: 13,
      fontFamily: 'Inter_400Regular',
      color: isDark ? '#94a3b8' : '#64748b',
    },
    transAmount: {
      fontSize: 16,
      fontWeight: 'bold',
      marginLeft: 8,
      fontFamily: 'Inter_700Bold',
      color: '#1fa97c',
    },
  });
};
