import { StyleSheet } from 'react-native';

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 0,
    paddingBottom: 0,
    paddingHorizontal: 0,
  },
  gradient: {
    flex: 1,
    paddingTop: 0,
    paddingBottom: 0,
    paddingHorizontal: 0,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 56,
    paddingBottom: 18,
    paddingHorizontal: 20,
  },
  logo: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  appName: {
    flex: 1,
    fontSize: 28,
    fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: 'Inter_700Bold',
  },
  avatarBox: {
    width: 44,
    height: 44,
    borderRadius: 16,
    backgroundColor: '#dbeafe',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 12,
  },
  savingCard: {
    marginTop: 0,
    borderRadius: 28,
    padding: 28,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 6,
    marginBottom: 18,
  },
  savingLabel: {
    fontSize: 18,
    fontWeight: '500',
    fontFamily: 'Inter_500Medium',
  },
  savingAmount: {
    fontSize: 40,
    fontWeight: 'bold',
    marginVertical: 6,
    fontFamily: 'Inter_700Bold',
  },
  savingSub: {
    fontSize: 15,
    marginBottom: 18,
    fontFamily: 'Inter_400Regular',
  },
  actionRow: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    marginTop: 10,
    gap: 8,
  },
  addBtn: {
    flex: 1,
    borderRadius: 16,
    marginRight: 8,
    paddingVertical: 16,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    shadowColor: '#1fa97c',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 4,
  },
  addBtnText: {
    fontWeight: 'bold',
    fontSize: 18,
    fontFamily: 'Inter_700Bold',
  },
  withdrawBtn: {
    flex: 1,
    borderRadius: 16,
    marginLeft: 8,
    paddingVertical: 16,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    shadowColor: '#e74c3c',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 4,
  },
  withdrawBtnText: {
    fontWeight: 'bold',
    fontSize: 18,
    fontFamily: 'Inter_700Bold',
  },
  card: {
    borderRadius: 24,
    marginHorizontal: 16,
    marginTop: 18,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  cardTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 12,
    fontFamily: 'Inter_700Bold',
  },
  historyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
    paddingVertical: 4,
  },
  circle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  plus: {},
  minus: {},
  circleText: {
    fontWeight: 'bold',
    fontSize: 20,
  },
  historyLabel: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Inter_500Medium',
  },
  historyDate: {
    fontSize: 13,
    fontFamily: 'Inter_400Regular',
  },
  historyId: {
    fontSize: 13,
    marginLeft: 8,
    fontFamily: 'Inter_400Regular',
  },
  transRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
    paddingVertical: 4,
  },
  transIconBox: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  transIcon: {
    width: 20,
    height: 20,
    borderRadius: 6,
  },
  transLabel: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Inter_500Medium',
  },
  transDate: {
    fontSize: 13,
    fontFamily: 'Inter_400Regular',
  },
  transAmount: {
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 8,
    fontFamily: 'Inter_700Bold',
  },
});
